#!/bin/bash

echo "----------------------"
echo "- Install MagixCubic -"
echo "----------------------"
echo ""

make -f ./makefile.auto appinstall
if [[ $? != 0 ]]; then
	out="report error on https://github.com/vbextreme/MagixCubic/issues"
	./easystatus $out
	./easystatus -e
	exit 1
fi
./easystatus "install"
./easystatus -o

echo "------------"
echo "- Complete -"
echo "------------"
echo ""

